// Generated by nitro
import type { Serialize, Simplify } from "nitropack";
declare module "nitropack" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
  interface InternalApi {
    "/api/user": {
      default: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/api/user").default>>>>;
    };
    "/author": {
      default: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/author").default>>>>;
    };
    "/draft-list": {
      get: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/draft-list.get").default>>>>;
    };
    "/feed": {
      get: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/feed.get").default>>>>;
    };
    "/filterPosts": {
      get: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/filterPosts.get").default>>>>;
    };
    "/post/:id": {
      delete: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/post/[id].delete").default>>>>;
      get: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/post/[id].get").default>>>>;
    };
    "/post": {
      default: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/post/index").default>>>>;
    };
    "/publish/:id": {
      put: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/publish/[id].put").default>>>>;
    };
    "/user": {
      default: Simplify<Serialize<Awaited<ReturnType<typeof import("../../server/routes/user").default>>>>;
    };
    "/__nuxt_error": {
      default: Simplify<
        Serialize<
          Awaited<ReturnType<typeof import("../../node_modules/nuxt/dist/core/runtime/nitro/renderer").default>>
        >
      >;
    };
  }
}
export {};
